(function(global){

    var app = global.app = global.app || {};

    function getData(){
        return      [
                          {
                              "id": "fba28a4a-177d-444c-8901-3cf65232cfe8",
                              "Company": "odlo-ch",
                              "Url": "http://www.sap.com",
                              "Picture": "http://robohash.org/55bee6cd-2e0c-479b-8738-4735545c3f12?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": true,
                              "CustomerCity": "Coldiron",
                              "CustomerFirstName": "Walsh",
                              "CustomerLastName": "Mercado",
                              "CustomerHotel": "TASMANIA",
                              "PaymentTypes": "Bar",
                              "ScanCodes": "\"5345343453453453\"",
                              "ReceiptType": 9,
                              "ReceiptNo": 8,
                              "ReceiptId": 10,
                              "CashDeskNo": 12,
                              "Timestamp": "2014-11-28T22:33.52Z",
                              "ReceiptDate": "2014-07-25T05:38.05Z"
                          },
                          {
                              "id": "240028b1-9ae4-42d8-bcb1-83b14a349fbc",
                              "Company": "odlo-ch",
                              "Url": "http://www.google.com",
                              "Picture": "http://robohash.org/39533419-80ad-4403-8e93-13e98da201ab?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": true,
                              "CustomerCity": "Moscow",
                              "CustomerFirstName": "Schmidt",
                              "CustomerLastName": "Rodgers",
                              "CustomerHotel": "CODAX",
                              "PaymentTypes": "Bar",
                              "ScanCodes": "\"64565464545456\"",
                              "ReceiptType": 1,
                              "ReceiptNo": 8,
                              "ReceiptId": 10,
                              "CashDeskNo": 10,
                              "Timestamp": "2014-05-23T19:08.58Z",
                              "ReceiptDate": "2014-01-11T12:27.44Z"
                          },
                          {
                              "id": "845a6dc7-1652-4ff9-a3e0-47e197c9a337",
                              "Company": "riml",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/dc37e187-7397-409f-9991-18ca25ac5a5b?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": false,
                              "CustomerCity": "Albrightsville",
                              "CustomerFirstName": "Christine",
                              "CustomerLastName": "Matthews",
                              "CustomerHotel": "ZYPLE",
                              "PaymentTypes": "VISA",
                              "ScanCodes": "\"8978934242342\"",
                              "ReceiptType": 10,
                              "ReceiptNo": 10,
                              "ReceiptId": 10,
                              "CashDeskNo": 11,
                              "Timestamp": "2014-04-24T21:20.12Z",
                              "ReceiptDate": "2014-03-23T00:44.18Z"
                          },
                          {
                              "id": "06ebbf71-55d9-4f73-bbe4-5d54cd2d96ad",
                              "Company": "odlo-de",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/6959ad5a-ae7d-455d-a816-e15ed38bb9f4?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": false,
                              "CustomerCity": "Clara",
                              "CustomerFirstName": "Trujillo",
                              "CustomerLastName": "Herman",
                              "CustomerHotel": "GRUPOLI",
                              "PaymentTypes": "VISA",
                              "ScanCodes": "\"1234567890123\"",
                              "ReceiptType": 8,
                              "ReceiptNo": 9,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-09-30T21:52.36Z",
                              "ReceiptDate": "2014-08-06T07:30.47Z"
                          },
                          {
                              "id": "0f5b4f0c-7b30-4a0f-8524-78d75d0015db",
                              "Company": "jades",
                              "Url": "http://www.google.com",
                              "Picture": "http://robohash.org/b3db284d-5ac5-4b04-8835-77e836b0520f?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": true,
                              "CustomerCity": "Fresno",
                              "CustomerFirstName": "House",
                              "CustomerLastName": "Bond",
                              "CustomerHotel": "KRAG",
                              "PaymentTypes": "Mastercard",
                              "ScanCodes": "\"543210987654\"",
                              "ReceiptType": 6,
                              "ReceiptNo": 8,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-11-24T21:25.47Z",
                              "ReceiptDate": "2014-02-03T02:27.50Z"
                          },
                          {
                              "id": "788af3f2-09ad-4459-beaa-f50e6d552a28",
                              "Company": "riml",
                              "Url": "http://www.sap.com",
                              "Picture": "http://robohash.org/c0025820-dfa7-4d62-9a34-670436679bfe?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": true,
                              "CustomerCity": "Callaghan",
                              "CustomerFirstName": "Anderson",
                              "CustomerLastName": "Malone",
                              "CustomerHotel": "GEOLOGIX",
                              "PaymentTypes": "EC-Cash",
                              "ScanCodes": "\"978786787564564\"",
                              "ReceiptType": 5,
                              "ReceiptNo": 10,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-10-08T02:34.00Z",
                              "ReceiptDate": "2014-11-19T07:33.39Z"
                          },
                          {
                              "id": "56a30337-5ec6-4dbf-a25d-90e9b61cf0e2",
                              "Company": "patscheider",
                              "Url": "http://www.google.com",
                              "Picture": "http://robohash.org/f124ef44-205e-493c-b1bb-3fe3de4472e6?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": true,
                              "CustomerCity": "Shindler",
                              "CustomerFirstName": "Shanna",
                              "CustomerLastName": "Hansen",
                              "CustomerHotel": "BICOL",
                              "PaymentTypes": "Bankomat",
                              "ScanCodes": "\"67567655675\"",
                              "ReceiptType": 4,
                              "ReceiptNo": 9,
                              "ReceiptId": 10,
                              "CashDeskNo": 11,
                              "Timestamp": "2014-02-05T17:25.30Z",
                              "ReceiptDate": "2014-11-05T16:15.21Z"
                          },
                          {
                              "id": "f89fdcf6-79ac-4691-a0fb-d1af2e20a21f",
                              "Company": "patscheider",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/731a045f-6aba-4b1e-b5a7-5201e7316070?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": false,
                              "CustomerCity": "Orason",
                              "CustomerFirstName": "Brandy",
                              "CustomerLastName": "Zamora",
                              "CustomerHotel": "TERRAGO",
                              "PaymentTypes": "Bar",
                              "ScanCodes": "\"67567655675\"",
                              "ReceiptType": 6,
                              "ReceiptNo": 9,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-06-25T08:01.48Z",
                              "ReceiptDate": "2014-10-26T10:24.27Z"
                          },
                          {
                              "id": "e6a3d596-916a-43d8-ae02-51327e5f4810",
                              "Company": "patscheider",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/a3124681-0f8d-45bc-8a27-e4c9b35843bf?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": true,
                              "CustomerCity": "Hiseville",
                              "CustomerFirstName": "Merritt",
                              "CustomerLastName": "Greene",
                              "CustomerHotel": "NURALI",
                              "PaymentTypes": "Bar",
                              "ScanCodes": "\"5353453453453453\"",
                              "ReceiptType": 4,
                              "ReceiptNo": 10,
                              "ReceiptId": 10,
                              "CashDeskNo": 9,
                              "Timestamp": "2014-03-22T10:56.28Z",
                              "ReceiptDate": "2014-07-19T00:24.26Z"
                          },
                          {
                              "id": "79e0e0b0-fe07-4551-86b1-a9fc56c53f12",
                              "Company": "retailtest",
                              "Url": "http://www.sap.com",
                              "Picture": "http://robohash.org/2df290b2-ff0b-4c2a-86e6-3c140393cd43?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": true,
                              "CustomerCity": "Calpine",
                              "CustomerFirstName": "Stacie",
                              "CustomerLastName": "Lynch",
                              "CustomerHotel": "ISOLOGIA",
                              "PaymentTypes": "Bankomat",
                              "ScanCodes": "\"1234567890123\"",
                              "ReceiptType": 2,
                              "ReceiptNo": 10,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-10-02T05:03.39Z",
                              "ReceiptDate": "2014-06-18T08:53.25Z"
                          },
                          {
                              "id": "1d61149b-a471-4e0e-b102-db8aef0001bc",
                              "Company": "retailtest",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/9ce95a84-0532-4a0b-88c4-4dee66cc9255?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": false,
                              "CustomerCity": "Hackneyville",
                              "CustomerFirstName": "Jeannette",
                              "CustomerLastName": "Norton",
                              "CustomerHotel": "ISOSTREAM",
                              "PaymentTypes": "Bankomat",
                              "ScanCodes": "\"543210987654\"",
                              "ReceiptType": 3,
                              "ReceiptNo": 9,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-11-17T15:14.16Z",
                              "ReceiptDate": "2014-09-04T19:51.50Z"
                          },
                          {
                              "id": "f27a27f0-6821-4531-99ef-020365b1399c",
                              "Company": "odlo-de",
                              "Url": "http://www.sap.com",
                              "Picture": "http://robohash.org/a49e718a-2b1d-453c-914a-16a7420992c2?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": false,
                              "CustomerCity": "Hilltop",
                              "CustomerFirstName": "Elba",
                              "CustomerLastName": "Davidson",
                              "CustomerHotel": "LUNCHPAD",
                              "PaymentTypes": "Mastercard",
                              "ScanCodes": "\"1234567890123\"",
                              "ReceiptType": 1,
                              "ReceiptNo": 10,
                              "ReceiptId": 10,
                              "CashDeskNo": 11,
                              "Timestamp": "2014-03-18T15:29.26Z",
                              "ReceiptDate": "2014-04-23T02:59.41Z"
                          },
                          {
                              "id": "02c988a2-001b-4b91-aaad-eedf4e9856b2",
                              "Company": "sperk",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/6bb17b2a-33ff-4bd2-a2f9-029be81d6d4f?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": false,
                              "CustomerCity": "Charco",
                              "CustomerFirstName": "Rocha",
                              "CustomerLastName": "Melendez",
                              "CustomerHotel": "NETUR",
                              "PaymentTypes": "VISA",
                              "ScanCodes": "\"543210987654\"",
                              "ReceiptType": 6,
                              "ReceiptNo": 10,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-05-03T22:45.03Z",
                              "ReceiptDate": "2014-09-27T07:45.33Z"
                          },
                          {
                              "id": "299ef3e8-af1d-498c-b567-5e769510953e",
                              "Company": "odlo-de",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/e0649e8d-af18-4673-a20b-de5d1c5f9e8a?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": false,
                              "CustomerCity": "Morningside",
                              "CustomerFirstName": "Imelda",
                              "CustomerLastName": "Blankenship",
                              "CustomerHotel": "DUFLEX",
                              "PaymentTypes": "VISA",
                              "ScanCodes": "\"67567655675\"",
                              "ReceiptType": 1,
                              "ReceiptNo": 9,
                              "ReceiptId": 10,
                              "CashDeskNo": 13,
                              "Timestamp": "2014-03-09T17:25.12Z",
                              "ReceiptDate": "2014-03-17T13:44.34Z"
                          },
                          {
                              "id": "baf3637b-a395-48a5-b02b-e77434f800c2",
                              "Company": "sperk",
                              "Url": "http://www.sap.com",
                              "Picture": "http://robohash.org/fb33590f-8ff8-4a73-8e28-cc6e56c09a99?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": false,
                              "CustomerCity": "Cascades",
                              "CustomerFirstName": "Lucille",
                              "CustomerLastName": "Valencia",
                              "CustomerHotel": "PROSELY",
                              "PaymentTypes": "VISA",
                              "ScanCodes": "\"23243242323423\"",
                              "ReceiptType": 5,
                              "ReceiptNo": 7,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-04-08T01:27.10Z",
                              "ReceiptDate": "2014-05-30T17:12.38Z"
                          },
                          {
                              "id": "9c6317d0-ddaa-4326-9d06-de11d970c279",
                              "Company": "odlo-ch",
                              "Url": "http://www.google.com",
                              "Picture": "http://robohash.org/71f48465-2de2-4f36-975f-8b2271fee1d2?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": false,
                              "CustomerCity": "Enlow",
                              "CustomerFirstName": "Terra",
                              "CustomerLastName": "Hewitt",
                              "CustomerHotel": "JAMNATION",
                              "PaymentTypes": "EC-Cash",
                              "ScanCodes": "\"67567655675\"",
                              "ReceiptType": 5,
                              "ReceiptNo": 7,
                              "ReceiptId": 10,
                              "CashDeskNo": 15,
                              "Timestamp": "2014-05-05T18:23.43Z",
                              "ReceiptDate": "2014-01-14T04:02.34Z"
                          },
                          {
                              "id": "7dcefbb4-d21f-4a6a-81b7-30f72abfaa1b",
                              "Company": "retailtest",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/29a359bf-9f0a-471b-9ecc-5d42c97192dc?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": false,
                              "CustomerCity": "Ripley",
                              "CustomerFirstName": "Shelton",
                              "CustomerLastName": "Sosa",
                              "CustomerHotel": "BLEEKO",
                              "PaymentTypes": "EC-Cash",
                              "ScanCodes": "\"1234567890123\"",
                              "ReceiptType": 5,
                              "ReceiptNo": 9,
                              "ReceiptId": 10,
                              "CashDeskNo": 15,
                              "Timestamp": "2014-06-08T14:40.56Z",
                              "ReceiptDate": "2014-07-23T22:46.22Z"
                          },
                          {
                              "id": "4a6c8fc8-e315-4099-8b91-21b6a7a71cd1",
                              "Company": "sperk",
                              "Url": "http://www.yahoo.com",
                              "Picture": "http://robohash.org/04967864-3be6-4814-89a0-5977998ea0d6?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": false,
                              "CustomerCity": "Yukon",
                              "CustomerFirstName": "Geraldine",
                              "CustomerLastName": "Velasquez",
                              "CustomerHotel": "KAGE",
                              "PaymentTypes": "VISA",
                              "ScanCodes": "\"978786787564564\"",
                              "ReceiptType": 9,
                              "ReceiptNo": 7,
                              "ReceiptId": 10,
                              "CashDeskNo": 14,
                              "Timestamp": "2014-05-22T17:52.53Z",
                              "ReceiptDate": "2014-08-23T12:29.41Z"
                          },
                          {
                              "id": "e9551334-732e-4fe7-94bf-ce4db3964b4e",
                              "Company": "retailtest",
                              "Url": "http://www.sap.com",
                              "Picture": "http://robohash.org/d5ddcd31-1f77-4c03-8b1c-1279c757ff31?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": true,
                              "CustomerCity": "Blairstown",
                              "CustomerFirstName": "Shelly",
                              "CustomerLastName": "Torres",
                              "CustomerHotel": "PETICULAR",
                              "PaymentTypes": "Bankomat",
                              "ScanCodes": "\"1234567890123\"",
                              "ReceiptType": 1,
                              "ReceiptNo": 7,
                              "ReceiptId": 10,
                              "CashDeskNo": 13,
                              "Timestamp": "2014-07-15T15:27.18Z",
                              "ReceiptDate": "2014-06-05T22:34.51Z"
                          },
                          {
                              "id": "69f49bd1-31d8-4173-8640-6e3b652463da",
                              "Company": "jades",
                              "Url": "http://www.google.com",
                              "Picture": "http://robohash.org/990bde3b-e42f-424e-9eab-9a8317d41d47?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": true,
                              "CustomerCity": "Leola",
                              "CustomerFirstName": "Dianna",
                              "CustomerLastName": "Rich",
                              "CustomerHotel": "VIRXO",
                              "PaymentTypes": "Bankomat",
                              "ScanCodes": "\"23243242323423\"",
                              "ReceiptType": 8,
                              "ReceiptNo": 10,
                              "ReceiptId": 10,
                              "CashDeskNo": 12,
                              "Timestamp": "2014-10-27T03:40.59Z",
                              "ReceiptDate": "2014-01-26T12:17.33Z"
                          },
                          {
                              "id": "8b510c9f-0327-4846-8751-16a09f7bf47d",
                              "Company": "odlo-de",
                              "Url": "http://www.google.com",
                              "Picture": "http://robohash.org/23ee6773-7c82-4125-be3d-0d686931714a?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": true,
                              "CustomerCity": "Caroline",
                              "CustomerFirstName": "Tania",
                              "CustomerLastName": "Kirkland",
                              "CustomerHotel": "DOGNOSIS",
                              "PaymentTypes": "EC-Cash",
                              "ScanCodes": "\"5345343453453453\"",
                              "ReceiptType": 9,
                              "ReceiptNo": 9,
                              "ReceiptId": 10,
                              "CashDeskNo": 12,
                              "Timestamp": "2014-09-26T05:27.49Z",
                              "ReceiptDate": "2014-03-16T10:07.37Z"
                          },
                          {
                              "id": "126146cc-fa16-43e3-b310-2ee0edff3b53",
                              "Company": "odlo-ch",
                              "Url": "http://www.google.com",
                              "Picture": "http://robohash.org/e3f9b45c-a2a1-4409-8151-40f77b38dfeb?set=set2&size=60x60",
                              "Gender": "female",
                              "Active": true,
                              "CustomerCity": "Cawood",
                              "CustomerFirstName": "Selma",
                              "CustomerLastName": "Meyer",
                              "CustomerHotel": "MELBACOR",
                              "PaymentTypes": "Bar",
                              "ScanCodes": "\"675656435343\"",
                              "ReceiptType": 2,
                              "ReceiptNo": 7,
                              "ReceiptId": 10,
                              "CashDeskNo": 15,
                              "Timestamp": "2014-06-21T13:44.12Z",
                              "ReceiptDate": "2014-02-01T10:39.25Z"
                          },
                          {
                              "id": "dfd0430b-9da5-4d3b-8cce-6c94bcb2d211",
                              "Company": "retailtest",
                              "Url": "http://www.sap.com",
                              "Picture": "http://robohash.org/a052c18e-6db7-45bc-974d-f38a171d1298?set=set2&size=60x60",
                              "Gender": "male",
                              "Active": false,
                              "CustomerCity": "Torboy",
                              "CustomerFirstName": "Callahan",
                              "CustomerLastName": "Reilly",
                              "CustomerHotel": "APEXTRI",
                              "PaymentTypes": "VISA",
                              "ScanCodes": "\"23243242323423\"",
                              "ReceiptType": 6,
                              "ReceiptNo": 7,
                              "ReceiptId": 10,
                              "CashDeskNo": 9,
                              "Timestamp": "2014-03-10T07:10.46Z",
                              "ReceiptDate": "2014-05-27T14:46.05Z"
                          },
                          
                         
                      ]
    };

    function getModel(data) {
        var model = new sap.ui.model.json.JSONModel();
        model.setData({ modelData: data });
        return model;
    }

    app.models = {
        getData: getData,
        getModel: getModel
    };

}(window));